version: '3.7'

services:
  zipline:
    image: ghcr.io/diced/zipline
    environment:
      - WEBSITE_TITLE=i.luac.es File Share
      - WEBSITE_SHOW_FILES_PER_USER=true
      - UPLOADER_ADMIN_LIMIT=250mb
      - CORE_PORT=3000
      - CORE_RETURN_HTTPS=true
      - DATASOURCE_TYPE=s3
      - CORE_SECRET=${CORE_SECRET}
      - CORE_DATABASE_URL=${CORE_DATABASE_URL}
      - DATASOURCE_S3_ACCESS_KEY_ID=${DATASOURCE_S3_ACCESS_KEY_ID}
      - DATASOURCE_S3_SECRET_ACCESS_KEY=${DATASOURCE_S3_SECRET_ACCESS_KEY}
      - DATASOURCE_S3_ENDPOINT=s3.amazonaws.com
      - DATASOURCE_S3_BUCKET=${DATASOURCE_S3_BUCKET}
      - DATASOURCE_S3_REGION=us-east-1
      - DATASOURCE_S3_FORCE_S3_PATH=false
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.raluaces-zipline-http.rule=Host(`z.luac.es`, `i.luac.es`)
        - traefik.http.routers.raluaces-zipline-http.entrypoints=http
        - traefik.http.routers.raluaces-zipline-http.middlewares=https-redirect
        - traefik.http.routers.raluaces-zipline-https.rule=Host(`z.luac.es`, `i.luac.es`)
        - traefik.http.routers.raluaces-zipline-https.entrypoints=https
        - traefik.http.routers.raluaces-zipline-https.tls=true
        - traefik.http.services.raluaces-zipline-https.loadbalancer.server.port=3000
    volumes:
      - /data/docker/raluaces-zipline:/zipline/uploads
    networks:
      - postgres
      - traefik-public

networks:
  traefik-public:
    external: true
  postgres:
    external: true
