version: '3.7'

services:
  zipline:
    image: ghcr.io/diced/zipline
    environment:
      - WEBSITE_TITLE=CSSNR
      - WEBSITE_EXTERNAL_LINKS=[{"label":"Uptime Kuma","link":"https://uptime.nj.hosted-domains.com/"},{"label":"PGAdmin","link":"https://pgadmin.hosted-domains.com/"},{"label":"Portainer","link":"https://portainer-o-us-east-1.hosted-domains.com/"}]
      - CORE_PORT=3000
      - CORE_SECRET=${CORE_SECRET}
      - CORE_DATABASE_URL=${CORE_DATABASE_URL}
      - FEATURES_OAUTH_REGISTRATION=true
      - OAUTH_DISCORD_CLIENT_ID=${OAUTH_DISCORD_CLIENT_ID}
      - OAUTH_DISCORD_CLIENT_SECRET=${OAUTH_DISCORD_CLIENT_SECRET}
      - CORE_RETURN_HTTPS=true
    deploy:
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.shane-zipline-http.rule=Host(`i.cssnr.com`)
        - traefik.http.routers.shane-zipline-http.entrypoints=http
        - traefik.http.routers.shane-zipline-http.middlewares=https-redirect
        - traefik.http.routers.shane-zipline-https.rule=Host(`i.cssnr.com`)
        - traefik.http.routers.shane-zipline-https.entrypoints=https
        - traefik.http.routers.shane-zipline-https.tls=true
        - traefik.http.services.shane-zipline-https.loadbalancer.server.port=3000
    volumes:
      - /data/docker/shane-zipline:/zipline/uploads
    networks:
      - postgres
      - traefik-public

networks:
  traefik-public:
    external: true
  postgres:
    external: true
